name: truckinnout-server
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: truckinnout-dev
    command: sh -c "python manage.py makemigrations --no-input && python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SETTINGS_MODULE: truckinnout_backend.settings
      AWS_QUERYSTRING_EXPIRE: ${AWS_QUERYSTRING_EXPIRE}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}
      AWS_S3_SIGNATURE_VERSION: ${AWS_S3_SIGNATURE_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_HOST: ${RESEND_HOST}
      DEFAULT_FILE_STORAGE: ${DEFAULT_FILE_STORAGE}
      DB_URL: ${DB_URL}
      STATIC_URL: static/
      STATIC_ROOT: /truckinnout-backend/staticfiles
      MEDIA_URL: /media/
      MEDIA_ROOT: /truckinnout-backend/static/images
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - .:/truckinnout-backend
      - /truckinnout-backend/.venv
    working_dir: /truckinnout-backend
